
import Head from "next/head";
import styles from "../styles/Home.module.css";
import PictureCard from "../components/PictureCard";
import { useSelector } from 'react-redux'
import { Typography } from "@mui/material";

export default function MyFavorites() {
    const favorites = useSelector(state => state.favorites.images)
    return (
      <div>
        <Head>
          <title>My Favorite NASA Pictures</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.main}>
          {!favorites.length ? <Typography> You have no favorites!</Typography> : favorites.map((image) => {
            const { title, url, hdurl, desc, date } = image;
            return (
              <div key={url} className={styles.card}>
              <PictureCard
                title={title}
                url={url}
                hdurl={hdurl}
                desc={desc}
                date={date}
              />
              </div>
            );
          })}
        </div>
      </div>
    );
}