
import Head from "next/head";
import styles from "../styles/Home.module.css";
import PictureCard from "../components/PictureCard";
import Link from "next/link"
import Button from '@mui/material/Button';
import { useDispatch, useSelector } from 'react-redux'

export default function MyFavorites() {
    const dispatch = useDispatch()
    const favorites = useSelector(state => state.favorites.images)
    return (
      <div>
        <Head>
          <title>My Favorite NASA Pictures</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <div className={styles.main}>
          {favorites.map((image) => {
            const { title, url, hdurl, desc, date } = image;
            return (
              <div key={url} className={styles.card}>
              <PictureCard
                title={title}
                url={url}
                hdurl={hdurl}
                desc={desc}
                date={date}
              />
              </div>
            );
          })}
        </div>
  
        <footer className={styles.footer}>
          <Link href="/"><Button variant='text'>More</Button></Link>
        </footer>
      </div>
    );
}